[project]
name = "scp"
version = "0.1.0"
description = "Python wrapper for Sony Camera Remote SDK (C++)"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "pybind11>=2.13.6",
]
